In [1]:
import numpy as np

In [5]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
import pandas as pd
df = pd.DataFrame(arr)
type(df.values)

numpy.ndarray

In [8]:
arr = arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
arr = arr.reshape(4,1,5)
arr

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20]]])

In [11]:
arr = arr.reshape(2,2,5)
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [12]:
arr = arr.reshape(1,4,5)
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [13]:
arr = arr.reshape(4,1,1,5)
arr

array([[[[ 1,  2,  3,  4,  5]]],


       [[[ 6,  7,  8,  9, 10]]],


       [[[11, 12, 13, 14, 15]]],


       [[[16, 17, 18, 19, 20]]]])

In [15]:
arr = arr.reshape(1,2,2,5)
arr

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [17]:
arr = arr.reshape(2,1,2,5)
arr

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [21]:
arr = arr.reshape(5,2,1,2)
arr.shape

(5, 2, 1, 2)

In [22]:
arr = arr[:,np.newaxis]
arr.shape

(5, 1, 2, 1, 2)

In [27]:
arr = arr.reshape(-1)
arr = arr[:,np.newaxis]
print(arr.shape)
print(arr)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


### 练习1

In [34]:
arr0 = np.arange(1,21)
print(arr0)
arr01 = arr0[::3]
print(arr01)
arr0 = arr0.reshape(4,5)
print(arr0,arr0.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  4  7 10 13 16 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5)


In [35]:
arr0[:,::2]*=2
arr0

array([[ 2,  2,  6,  4, 10],
       [12,  7, 16,  9, 20],
       [22, 12, 26, 14, 30],
       [32, 17, 36, 19, 40]])

In [37]:
arr0[:,1::2]-=3
arr0

array([[ 2, -4,  6, -2, 10],
       [12,  1, 16,  3, 20],
       [22,  6, 26,  8, 30],
       [32, 11, 36, 13, 40]])

### 练习2

In [38]:
arr1 = np.arange(1,25)
print(arr1)
arr1 = arr1.astype(np.int64)
print(arr1.dtype)
np.random.shuffle(arr1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
int64
[16 10  5  1 12 18  8  7 11  4 24 20  3 17  9 14 15 23 19 21  2  6 22 13]


In [59]:
arr1 = arr1.reshape(2,3,4)
print(arr1)
max1 = np.max(arr1,axis = 2 )
print(max1)
print(max1.shape)

[[[16 10  5  1]
  [12 18  8  7]
  [11  4 24 20]]

 [[ 3 17  9 14]
  [15 23 19 21]
  [ 2  6 22 13]]]
[[16 18 24]
 [17 23 22]]
(2, 3)
